### ISSUE TITLE
Mike Smith's presentation

### ISSUE THREAD

**Issue by microsmith** [skimedic/cincydeliverpresentations#24]
Phil, here's the PPT 
[CoreMVC.pptx](https://github.com/skimedic/cincydeliverpresentations/files/3510915/CoreMVC.pptx)

or the PDF if you prefer...
[CoreMVC.pdf](https://github.com/skimedic/cincydeliverpresentations/files/3510918/CoreMVC.pdf)

**Comment by skimedic** [comment]
added. Thanks!
