### ISSUE TITLE
Agile Team Development Lifecycle presentation

### ISSUE THREAD

**Issue by robbiesykes** [skimedic/cincydeliverpresentations#26]
Here's the presentation from the "The Agile Team Development Lifecycle" presentation. (Friday, 11AM session in Sterling.)

[The Agile Team Development Lifecycle.pdf](https://github.com/skimedic/cincydeliverpresentations/files/3521502/The.Agile.Team.Development.Lifecycle.pdf)

**Comment by skimedic** [comment]
Added. Thanks!
